-- Step 78: profiles for the named hybrids people buy. Run after step 77.
--
-- Adds Red Texas Cichlid, Tibee Shrimp and Taiwan Bee Shrimp (with its King Kong and
-- Shadow Panda lines), moves Blue Bolt under Taiwan Bee (it was filed as a crystal red),
-- and links the crosses that make them, so their pages show "What it was bred from".
-- Fact-checked separately. Safe to run more than once: species that already exist are skipped.

begin;

insert into public.species (slug, common_name, scientific_name, also_known_as, former_names, trade_codes, group_name, family, genus, water_type, temp_min_f, temp_max_f, ph_min, ph_max, gh_min, gh_max, max_size_in, min_tank_gal, temperament, social, min_group_size, swim_level, diet, fin_nipper, plant_safe, care_level, suitability, breeding_type, lifespan, origin, summary, body, entry_type, parent_slug, described)
select v.slug, v.common_name, v.scientific_name, v.also_known_as, v.former_names, v.trade_codes, v.group_name, v.family, v.genus, v.water_type, v.temp_min_f, v.temp_max_f, v.ph_min, v.ph_max, v.gh_min, v.gh_max, v.max_size_in, v.min_tank_gal, v.temperament, v.social, v.min_group_size, v.swim_level, v.diet, v.fin_nipper, v.plant_safe, v.care_level, v.suitability, v.breeding_type, v.lifespan, v.origin, v.summary, v.body, v.entry_type, v.parent_slug, v.described
from (values
  ($v$red-texas-cichlid$v$, $v$Red Texas Cichlid$v$, $v$Cichlid hybrid$v$, array[$v$Red Texas$v$, $v$Super Red Texas$v$]::text[], '{}'::text[], '{}'::text[], $v$Cichlids - New World$v$, $v$Cichlidae$v$, null, $v$Freshwater$v$, 75, 82, 6.5, 8.0, 8, 20, 12, 75, $v$Aggressive$v$, $v$Solitary$v$, null, $v$All$v$, $v$Omnivore$v$, false, false, $v$Intermediate$v$, $v$Intermediate$v$, $v$Substrate spawner$v$, $v$10-15 years$v$, $v$Aquarium hybrid$v$, $v$A man-made hybrid with the Texas cichlid's pearly spangles on a red body; top grades sell for high prices.$v$, $v$Red Texas come from crossing Texas cichlids with red hybrid cichlids. Most sources name the flowerhorn or the blood parrot as the other parent, but the exact recipe is debated and differs between breeders. Colors vary a lot, and the red usually develops as the fish grows. Like its Texas parent it is big, strong and territorial, so it is best kept alone in a large tank with strong filtration and heavy rocks it can't knock over. Many can breed, but the young come out very mixed and few look like their parents.$v$, $v$species$v$, null, false),
  ($v$tibee-shrimp$v$, $v$Tibee Shrimp$v$, $v$Caridina hybrid$v$, array[$v$Tiger Bee Shrimp$v$, $v$Tibee$v$]::text[], '{}'::text[], '{}'::text[], $v$Shrimp$v$, $v$Atyidae$v$, $v$Caridina$v$, $v$Freshwater$v$, 68, 76, 6.0, 7.0, 4, 8, 1.2, 10, $v$Peaceful$v$, $v$Colony$v$, 10, $v$Bottom$v$, $v$Omnivore$v$, false, true, $v$Intermediate$v$, $v$Intermediate$v$, $v$Egg carrier$v$, $v$1-2 years$v$, $v$Aquarium hybrid of bee and tiger shrimp$v$, $v$A cross between bee shrimp and tiger shrimp, bred for new patterns and used to make Pinto lines.$v$, $v$Tibees come from crossing bee shrimp (crystal red, crystal black or Taiwan Bee) with tiger shrimp. Their looks vary a lot, often tiger stripes over a crystal-like base. Crossed back with Taiwan Bees they give Taitibees, the starting point for Pinto shrimp. Keep them like their parents: cool, soft, slightly acidic water over an active soil, in a mature tank with no fish. They breed with both parent lines, so keep them away from pure crystal or tiger colonies. Never use copper medications or plant products in their tank, since copper is deadly to shrimp.$v$, $v$species$v$, null, false),
  ($v$taiwan-bee-shrimp$v$, $v$Taiwan Bee Shrimp$v$, $v$Caridina hybrid$v$, array[$v$Taiwan Bee$v$, $v$TB$v$]::text[], '{}'::text[], '{}'::text[], $v$Shrimp$v$, $v$Atyidae$v$, $v$Caridina$v$, $v$Freshwater$v$, 68, 76, 5.8, 6.8, 4, 6, 1.2, 10, $v$Peaceful$v$, $v$Colony$v$, 10, $v$Bottom$v$, $v$Omnivore$v$, false, true, $v$Advanced$v$, $v$Advanced$v$, $v$Egg carrier$v$, $v$1-2 years$v$, $v$Selectively bred in Taiwan from crystal bee lines; exact ancestry debated$v$, $v$The Taiwan-bred bee shrimp lines, from solid colors like Blue Bolt and King Kong to patterns like Shadow Panda.$v$, $v$Taiwan Bees were developed in Taiwan from crystal red and crystal black bee shrimp. Many believe other Caridina, such as tiger shrimp, went into some lines; the exact history is debated. They are prized for solid blue, black, wine red and white colors and for patterned lines like Panda and Mosura. They need the same soft, acidic, very clean water as crystal reds: remineralized RO water over an active soil, kept cool and stable. They interbreed with crystal and bee shrimp, and most of the first generation young look like ordinary crystals (breeders call them mischlings) while carrying Taiwan Bee genes, so keep lines apart. Never use copper medications or plant products in their tank, since copper is deadly to shrimp.$v$, $v$species$v$, null, false),
  ($v$king-kong-shrimp$v$, $v$King Kong Shrimp$v$, $v$Caridina hybrid$v$, array[$v$King Kong Bee$v$, $v$Black King Kong$v$]::text[], '{}'::text[], '{}'::text[], $v$Shrimp$v$, $v$Atyidae$v$, $v$Caridina$v$, $v$Freshwater$v$, 68, 76, 5.8, 6.8, 4, 6, 1.2, 10, $v$Peaceful$v$, $v$Colony$v$, 10, $v$Bottom$v$, $v$Omnivore$v$, false, true, $v$Advanced$v$, $v$Advanced$v$, $v$Egg carrier$v$, $v$1-2 years$v$, $v$Taiwan Bee color line$v$, $v$A solid black Taiwan Bee line, sometimes with a bluish sheen.$v$, $v$King Kongs are a Taiwan Bee line with solid black bodies, and Shadow lines carry a bluish shine. Panda and Shadow Panda are close relatives in the same black family. Care is the same as other Taiwan Bees: cool, soft, acidic, very stable water in a mature tank with no fish.$v$, $v$variety$v$, $v$taiwan-bee-shrimp$v$, false),
  ($v$shadow-panda-shrimp$v$, $v$Shadow Panda Shrimp$v$, $v$Caridina hybrid$v$, array[$v$Shadow Panda$v$, $v$Blue Shadow Panda$v$]::text[], '{}'::text[], '{}'::text[], $v$Shrimp$v$, $v$Atyidae$v$, $v$Caridina$v$, $v$Freshwater$v$, 68, 76, 5.8, 6.8, 4, 6, 1.2, 10, $v$Peaceful$v$, $v$Colony$v$, 10, $v$Bottom$v$, $v$Omnivore$v$, false, true, $v$Advanced$v$, $v$Advanced$v$, $v$Egg carrier$v$, $v$1-2 years$v$, $v$Taiwan Bee color line$v$, $v$A Taiwan Bee line with dark blue-black and white bands.$v$, $v$Shadow Pandas have the banded Panda pattern, but the dark bands are a deep blue-black with a shimmer from the Shadow line, set against white bands. Care is the same as other Taiwan Bees: cool, soft, acidic, very stable water in a mature tank with no fish.$v$, $v$variety$v$, $v$taiwan-bee-shrimp$v$, false)
) as v(slug, common_name, scientific_name, also_known_as, former_names, trade_codes, group_name, family, genus, water_type, temp_min_f, temp_max_f, ph_min, ph_max, gh_min, gh_max, max_size_in, min_tank_gal, temperament, social, min_group_size, swim_level, diet, fin_nipper, plant_safe, care_level, suitability, breeding_type, lifespan, origin, summary, body, entry_type, parent_slug, described)
where not exists (select 1 from public.species s where s.slug = v.slug);

-- Blue Bolt is a Taiwan Bee line, not a crystal red.
update public.species
  set parent_slug = 'taiwan-bee-shrimp', also_known_as = array['Blue Bolt Taiwan Bee']::text[],
      origin = 'Taiwan Bee color line'
  where slug = 'blue-bolt-shrimp';

update public.species_crosses set result_slug = $v$tibee-shrimp$v$ where species_a = $v$bee-shrimp$v$ and species_b = $v$tiger-shrimp$v$;
update public.species_crosses set result_slug = $v$red-texas-cichlid$v$ where species_a = $v$flowerhorn-cichlid$v$ and species_b = $v$texas-cichlid$v$;
insert into public.species_crosses (species_a, species_b, outcome, note, confidence) values ($v$bee-shrimp$v$, $v$taiwan-bee-shrimp$v$, 'fertile', $v$Taiwan Bees breed freely with crystal and bee shrimp. Most first generation young look like plain crystals but carry Taiwan Bee genes, so keep the lines apart.$v$, 'high')
  on conflict (species_a, species_b) do update set outcome = excluded.outcome, note = excluded.note, confidence = excluded.confidence;

commit;
